services:
  quake-frontend:
    build:
      context: ./frontend
    container_name: bsg-21quake-frontend
    restart: unless-stopped
    networks:
      - default
      - holdem
    ports:
      - "3500:80"

networks:
  holdem:
    external: true
    name: 21holdem_default
