services:
  quake-screen:
    image: nginx:1.27-alpine
    container_name: bsg-21quake-screen
    restart: unless-stopped
    ports:
      - "3500:80"
    volumes:
      - ./src:/usr/share/nginx/html:ro
